type: "select"
title: "Act Immediately?"
optionSource:
  - title: "Act Immediately"
    description: "Act immediately before any character moves, move after all characters act"
    value: "yes"
  - title: "Move Before Acting"
    description: "Move after immediate actions, before all other characters act"
    value: "no"
    followUp: "prefab.move.yml"
