name: "action"
question:
  type: "select"
  title: "What action do you want to take?"
  key: "action"
  options:
    - title: "Attack"
      value: "attack"
      followUp:
        type: "dynamicSelect"
        title: "Select a creature or object to attack"
        key: "target"
        optionSource": "__targets__"
        followUp:
          type: "select"
          title: "Select a weapon to attack with"
          key: "weapon"
          options:
            - label: "Primary Melee, backup Ranged"
              value: "primaryMeleeBackupRanged"
              description: "Prefer primary melee weapon, use ranged as backup"
            - label: "Specific Weapon"
              value: "specificWeapon"
              description: "Use a specific weapon"
              followUp:
                type: "dynamicSelect"
                title: "Select a weapon"
                key: "weapon"
                optionSource: "__weapons__"
                followUp:
                  type: "text"
                  title: "Additional Notes"
                  key: "notes"
                  description: "Enter any additional notes about the attack"
    - title: "Magic"
      value: "magic"
      description: "Cast a spell"
      followUp:
        type: "dynamicSelect"
        title: "Select a spell"
        key: "spell"
        optionSource: "__spells__"
    - title: "Dash"
      value: "dash"
      description: "Move __attr.speed__ extra distance, you may apply this to your pre-action movement as well"
    - title: "Disengage"
      value: "disengage"
      description: "Move up to your speed without provoking opportunity attacks from hostile creatures"
    - title: "Help"
      value: "help"
      description: "Aid an ally in battle"
      followUp:
        type: "select"
        title: "Select an ally"
        key: "ally"
        optionSource: "__allies__"
        followUp:
          type: "select"
          title: "Select action to aid"
          options:
            - label: "Attack"
              value: "attack"
              followUp:
                type: "select"
                title: "Select a target"
                key: "target"
                optionSource: "__targets__"
            - label: "Ability Check"
              value: "abilityCheck"
              followUp:
                type: "select"
                title: "Select a proficiency or ability"
                key: "ability"
                options:
                  - label: "Acrobatics"
                  - label: "Animal Handling"
                  - label: "Arcana"
                  - label: "Athletics"
                  - label: "Deception"
                  - label: "History"
                  - label: "Insight"
                  - label: "Intimidation"
                  - label: "Investigation"
                  - label: "Medicine"
                  - label: "Nature"
                  - label: "Perception"
                  - label: "Performance"
                  - label: "Persuasion"
                  - label: "Religion"
                  - label: "Sleight of Hand"
                  - label: "Stealth"
                  - label: "Survival"
                  - label: "Strength"
                  - label: "Dexterity"
                  - label: "Constitution"
                  - label: "Intelligence"
                  - label: "Wisdom"
                  - label: "Charisma"
    - title: "Dodge"
      value: "dodge"
      description: "Attacks against you have disadvantage"
    - title: "Hide"
      value: "hide"
      description: "Attempt a DC 15 Stealth check to hide if you are in cover or obscured"
    - title: "Utilize an Object"
      value: "utilize"
      description: "Use an object to interact with the environment"
      followUp:
        type: "text"
        title: "Describe"
        key: "object"
        description: "Describe the object and your interaction with it"
    - title: "Influence"
      value: "influence"
      description: "Attempt an influence check to sway an enemy"
      followUp:
        type: "select"
        title: "Select a target"
        key: "target"
        optionSource: "__targets__"
        followUp:
          type: "select"
          title: "Select a method"
          key: "method"
          options:
            - label: "Persuasion"
              value: "persuasion"
              description: "Use persuasion to sway an enemy"
            - label: "Deception"
              value: "deception"
              description: "Use deception to sway an enemy"
            - label: "Performance"
              value: "performance"
              description: "Use performance to sway an enemy"
            - label: "Intimidation"
              value: "intimidation"
              description: "Use intimidation to sway an enemy"
          followUp:
            type: "text"
            title: "Describe"
            key: "notes"
            description: "Describe your interaction with the target"
    - title: "Search"
      value: "search"
      description: "Seek something"
      followUp:
        type: "select"
        title: "Select skill"
        key: "skill"
        options:
          - label: "Perception"
            value: "perception"
            description: "Use Perception to search for hidden or obscure things"
          - label: "Intuition"
            value: "intuition"
            description: "Use Intuition to evaluate a situation or interaction with a creature"
          - label: "Survival"
            value: "survival"
            description: "Use Survival to search (for food, water, etc)"
        followUp:
          type: "text"
          title: "Describe"
          key: "notes"
          description: "Describe your search"
    - title: "Study"
      value: "study"
      description: "Study something, such as information about a creature or object"
      followUp:
        type: "select"
        title: "Select skill"
        key: "skill"
        options:
          - label: "Investigation"
            value: "investigation"
            description: "Use Investigation to study"
          - label: "History"
            value: "history"
            description: "Use History to study"
          - label: "Religion"
            value: "religion"
            description: "Use Religion to study"
          - label: "Arcana"
            value: "arcana"
            description: "Use Arcana to study"
          - label: "Nature"
            value: "nature"
            description: "Use Nature to study"
        followUp:
          type: "text"
          title: "Describe"
          key: "notes"
          description: "Describe your examination or recollection"
  followUpSequence:
    - type: "select"
      title: "Bonus Action"
      key: "bonusAction"
      description: "Use a bonus action as part of your action"
      optionSource: "__bonusAction.action__"
    - type: "text"
      title: "Free Interaction"
      key: "freeInteraction"
      description: "Do something very quick, such as drawing or sheathing a weapon, opening a door, or speaking quickly"
