import { TurnViewLayout } from "../layouts/TurnViewLayout"

export const TurnViewHome = () => {
    return (
        <TurnViewLayout>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
            <h1>TurnViewHome</h1>
        </TurnViewLayout>
    )
}