orderOptions: "/orderOptions/default.yml"
description: "A fighter from the Red faction"
longDescription: "<p>A fighter from the Red faction</p><p>attacks with sword and javelin</p>"
name: "Red Fighter"
