name: "Capture the Flag v.3"
description: "The third 'Capture the Flag' playtest of D20 Tactics"

characters:
  - name: "Red Fighter"
    characterSheet: "/characterSheets/character.redFighter.yml"
    color: "red"
  - name: "Red Sorcerer"
    characterSheet: "/characterSheets/character.redFighter.yml"
    color: "red"
  - name: "Red Cleric"
    characterSheet: "/characterSheets/character.redFighter.yml"
    color: "red"
  - name: "Red Druid"
    characterSheet: "/characterSheets/character.redFighter.yml"
    color: "red"
  - name: "Blue Fighter"
    characterSheet: "/characterSheets/character.redFighter.yml"
    color: "blue"
  - name: "Blue Sorcerer"
    characterSheet: "/characterSheets/character.redFighter.yml"
    color: "blue"
  - name: "Blue Cleric"
    characterSheet: "/characterSheets/character.redFighter.yml"
    color: "blue"
  - name: "Blue Druid"
    characterSheet: "/characterSheets/character.redFighter.yml"
    color: "blue"

npcs:
  - name: "Red Pitchfork Peasants"
    characterSheet: "/characterSheets/npc.redPitchforkPeasants.yml"
    formation: 4
    color: "red"
  - name: "Blue Pitchfork Peasants"
    characterSheet: "/characterSheets/npc.bluePitchforkPeasants.yml"
    formation: 4
    color: "blue"
  - name: "Red Archer Peasants"
    characterSheet: "/characterSheets/npc.redArcherPeasants.yml"
    formation: 3
    color: "red"
  - name: "Blue Archer Peasants"
    characterSheet: "/characterSheets/npc.blueArcherPeasants.yml"
    formation: 3
    color: "blue"
  - name: "Red Knights"
    characterSheet: "/characterSheets/npc.redKnights.yml"
    formation: 2
    color: "red"
  - name: "Blue Knights"
    characterSheet: "/characterSheets/npc.blueKnights.yml"
    formation: 2
    color: "blue"
  - name: "Giant War Cleric"
    characterSheet: "/characterSheets/npc.giantWarCleric.yml"
    formation: 1
    color: "green"

objects:
  - name: "Flag"
    color: "green"
  - name: "Red Base"
    color: "red"
  - name: "Blue Base"
    color: "blue"
  - name: "South Cottage"
    color: "green"
  - name: "North Cottage"
    color: "green"
  - name: "Red Tower"
    color: "red"
  - name: "Blue Tower"
    color: "blue"
  - name: "Blue Wall"
    color: "blue"
  - name: "Red Wall"
    color: "red"

locations:
  - name: "Cover"
    color: "green"
  - name: "High ground"
    color: "green"
  - name: "North"
    color: "green"
  - name: "South"
    color: "green"
  - name: "East"
    color: "green"
  - name: "West"
    color: "green"
