name: "Default"
description: "This is a default character sheet"
turnSequence:
  - prefab: "prefab.move1.yml"
  - prefab: "prefab.action.yml"
  - prefab: "prefab.move2.yml"
  - prefab: "prefab.reaction.yml"
