name: "move1"
question:
  type: "select"
  value: "Motion Direction"
  options:
    - title: "Toward creature or object"
      description: "Move toward a creature or object"
      longDescription: "If you take the dash or disengage actions at any point in the turn, they apply to this movement"
      type: "select"
      value: "toward"
      optionSource: "__landmarks__"
      followUp:
        type: "text"
        value: "Notes"
        key: "notes"
        description: "Any notes on your movement"
        longDescription: "For instance 'avoid opportunity attacks' or 'take fall damage"
    - title: "Away from creature or object"
      value: "away"
      description: "Move away from a creature or object"
      longDescription: "If you take the dash or disengage actions at any point in the turn, they apply to this movement"
      followUp:
        type: "select"
        value: "specificMovement"
        optionSource: "__landmarks__"
    - title: "Specific Movement"
      description: "Describe a sequence of directional movements"
      longDescription: "If you take the dash or disengage actions at any point in the turn, they apply to this movement"
      value: "specificMovement"
      followUp:
        - type: "moveSequence"
          title: "Movement Sequence"
          value: "moveSequence"
  followUpSequence:
    - type: "select"
      title: "Use a Bonus Action?"
      key: "bonusAction"
      description: "Use a bonus action as part of your move?"
      optionSource: "__bonusAction.move1__"
    - type: "select"
      title: "Take a Free Interaction?"
      key: "freeInteraction"
      optionSource:
        - title: "No"
          value: "no"
        - title: "Yes"
          value: "yes"
          followUp:
            type: "text"
            title: "Free Interaction"
            key: "freeInteraction"
            description: "Do something very quick, such as drawing or sheathing a weapon, opening a door, or speaking quickly"
